### ISSUE TITLE
Go 1.9 is released. Seems like  don't support 1.9 stable build.

### ISSUE THREAD

**Issue by easonlin404** [travis-ci/gimme#107]
I add  `- 1.9.x` in my travis.yml And I got following message:
```
$ GIMME_OUTPUT=$(gimme 1.9.x | tee -a $HOME/.bashrc) && eval "$GIMME_OUTPUT"
I don't have any idea what to do with '1.9.x'.
```
Please help to figure out. Thanks.

**Comment by philpennock** [comment]
Opinion as an outside contributor to the gimme repo only: it's fair for people to file bugs like this against gimme, because it looks like gimme at fault, even though the .x mapping is entirely managed in the `travis-build` repo at a layer _above_ gimme.  People not closely involved shouldn't need to know that.

However, should we be doing more inside gimme?  Perhaps handling `.x` cleanly, or perhaps just saying "hey, we don't support `.x` handling here, something has failed to detect this before passing it to us", to give a more useful diagnostic?

**EDITED TO ADD: have opened #110 to discuss this**

**Comment by easonlin404** [comment]
@philpennock My apologies. I didn't awareness this. Sorry again. 😢

**Comment by philpennock** [comment]
No apologies; it was completely reasonable.  #110 filed to better support folks in this.
