### ISSUE TITLE
1.10.x selects "auto" instead of 1.10

### ISSUE THREAD

**Issue by purpleidea** [travis-ci/gimme#134]
As seen here: https://travis-ci.org/purpleidea/mgmt/jobs/343109782#L463

$ GIMME_OUTPUT="$(gimme 1.10.x | tee -a $HOME/.bashrc)" && eval "$GIMME_OUTPUT"
I don't have any idea what to do with '1.10.x'.
  (using type 'auto')

**Comment by philpennock** [comment]
At present, gimme does not interpret `.x`, that's done by the Travis CI build layer.

We have an open issue to add support, #110 
We have an open PR to add support (written by me): #130 

In the meantime, `gimme` has told you that it was _using_ type "auto" to try to find an image, not that the result it selected was "auto".  `$GIMME_TYPE` can be: `auto`, `binary`, `source`, `git`.  Gimme completely failed because it was given syntax which it does not understand, and won't understand until #130 or equivalent is merged.

**Comment by purpleidea** [comment]
@philpennock My apologies for the noise, and thanks for opening an issue in travis.

Cheers!
