### ISSUE TITLE
version of gimme

### ISSUE THREAD

**Issue by jellemaas** [travis-ci/gimme#155]
if you download gimme via homebrew you will get version 1.5.0 and "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.4 bash)" command won't work because GIMME_GO_VERSION=1.4 is not there but GIMME_GO_VERSION=1.5 is. I dont know if this is the case for all the other download methods as well but for every installation of go where 1.4 is in there instead of 1.5 it won't install, so maybe adjust READ.ME

**Comment by philpennock** [comment]
While I have a visceral loathing for `curl | bash` and would rather napalm any documents ever advocating that, in this case I'm not seeing what the bug report is trying to say.

The command you paste is missing the initial `eval `.  Otherwise, everything should work: the command is downloading a fresh copy of `gimme` (so the version from Homebrew is irrelevant) and then invoking `bash` on the script, telling it to install `Go 1.4`.

That you have Gimme 1.5.0 installed elsewhere is not relevant.

That you use Gimme to ask it to install Go 1.4 is not an issue.  It's a bit older than anything I bother ensuring compatibility with, but that is the point of Gimme: to install arbitrary versions.

You pipe the script to bash, telling the script to install version 1.4, and the script installs Go 1.4 from binary packages (probably), then produces on `stdout` shell directives to set various shell variables pointing to the version of Go which it just installed.

If you run `"$(curl ... | bash)"` then that's the same as running `"$(gimme)"`.  You'll get a shell error that a bunch of text is not a command to be invoked.  You need the `eval` there are the front.

The only way I see an error there is if you missed the `eval`, just as it's missing from the text of the bug-report.  If you did in fact type `eval`, please re-open this issue and provide more details, including the error message which you get.
