### ISSUE TITLE
gimme master returning go1.7 when env var is set

### ISSUE THREAD

**Issue by campoy** [travis-ci/gimme#158]
As seen on [this job](https://travis-ci.org/campoy/justforfunc/jobs/415781585),
`go version` is returning `go version go1.7.4 linux/amd64` even though the job configuration specifies `master`:

```json
{
  "go": "master",
  "os": "linux",
  "env": "GO111MODULE=on",
  "dist": "trusty",
  "group": "stable",
  "script": [
    "go test ./..."
  ],
  "language": "go"
}
```

```bash
$ GIMME_OUTPUT="$(gimme master | tee -a $HOME/.bashrc)" && eval "$GIMME_OUTPUT"
I don't have any idea what to do with 'master'.
  (using download type 'auto')
```

I tried moving the environment variable to the script and that fixed the issue. See [this job](https://travis-ci.org/campoy/justforfunc/jobs/415786582).

```json
{
  "go": "master",
  "os": "linux",
  "dist": "trusty",
  "group": "stable",
  "script": [
    "GO111MODULE=on go test ./..."
  ],
  "language": "go"
}
```

```bash
$ GIMME_OUTPUT="$(gimme master | tee -a $HOME/.bashrc)" && eval "$GIMME_OUTPUT"
go version devel +4fc7b93ad7 Mon Aug 13 19:04:16 2018 +0000 linux/amd64
```

Is this expected?

**Comment by joepvd** [comment]
Thanks for your report! This is indeed not expected.

We have been able to reproduce this, though the cause and fix are not clear.

**Comment by philpennock** [comment]
`GIMME_DEBUG=t GO111MODULE=on gimme master` shows that it's `make.bash` which fails.  Since `GO111MODULE=on` disables looking in `${^GOPATH}/src` (`src` in each element of `GOPATH`) and there's no `go.mod` stuff in the top-level of the Go repo's `src/` tree, it looks like `GO111MODULE=on` is incompatible with building Go itself.

Presumably the _intention_ here is to get current Go, then use the `GO111MODULE` for whatever is being tested _by_ "the system using Travis", not to use Gimme to build Go itself using that system.

IMO we should just unset `GO111MODULE` unconditionally from Travis, for builds, but not export that to the environment to influence things sourcing the output shell directives from Travis.
