### ISSUE TITLE
Gimme does not support apple silicon

### ISSUE THREAD

**Issue by gmmeyer** [travis-ci/gimme#195]
If I install gimme from homebrew, it gives me an error when I try to do anything

```
% brew install gimme
==> Downloading https://github.com/travis-ci/gimme/archive/v1.5.4.tar.gz
Already downloaded: /Users/greg/Library/Caches/Homebrew/downloads/9bc71a809f1d7e83d5fcb1de1a4c3eab3017d9a4ab9d19dd0ac046043f54e86b--gimme-1.5.4.tar.gz
🍺  /opt/homebrew/Cellar/gimme/1.5.4: 6 files, 40.7KB, built in 1 second

% gimme
error: arm64 is not supported by this go version
try go1.5 or newer
```

**Comment by tianon** [comment]
I'm not a super active maintainer on this repository, but wanted to note that this might end up being tricky due to (the yet unreleased) Go 1.16 being the first version of Go to actually support this hardware/OS combination.

If you explicitly request `1.16rc1`, it might "just work", so that's worth a try.

**Comment by gmmeyer** [comment]
yea the weird thing is that when you just do gimme it errors out, it seems to work when you do this! Thank you!
