### ISSUE TITLE
Doesn't seem to generate GOPATH

### ISSUE THREAD

**Issue by jamlen** [travis-ci/gimme#24]
**I'm very new to go!**

On OSX 10.10.2 I have installed gimme and ran `eval "$(gimme 1.4)"` and this sets the `GOROOT` env var but does not seem to set the `GOPATH` so I get:

``` shell
$ eval "$(gimme 1.4)"
go version go1.4 darwin/amd64
$ go get github.com/mitchellh/gox
package github.com/mitchellh/gox: cannot download, $GOPATH not set. For more details see: go help gopath
$ which go
/Users/jamlen/.gimme/versions/go1.4.darwin.amd64/bin/go
$ cat ~/.gimme/envs/latest.env

unset GOOS
unset GOARCH
export GOROOT="/Users/jamlen/.gimme/versions/go1.4.darwin.amd64"
export PATH="/Users/jamlen/.gimme/versions/go1.4.darwin.amd64/bin:${PATH}"
go version >&2
```

Should it be set?

**Comment by MrJoy** [comment]
I'm similarly confused about what the "right" way to approach this is.

**Comment by kofalt** [comment]
`GOPATH` isn't set by gimmie because it's a workspace configuration variable.
Generally you want to set it individually for each separate project.

A common script pattern I use a lot:

``` bash
#!/usr/bin/env bash

# Set cwd
unset CDPATH
cd "$( dirname "${BASH_SOURCE[0]}" )"

# Isolate this project's gopath
export GOPATH="$PWD"/.gopath/

# Run the go command you passed as args to the script!
go "$@"
```

I also ended up building a tiny tool to set up this sort of pattern, but [options abound](https://github.com/kofalt/golink#why).
The [official docs](https://golang.org/cmd/go/#hdr-GOPATH_environment_variable) have more.

**Comment by meatballhat** [comment]
Sorry for the long feedback loop, everyone!  As stated by others above, `GOPATH` is intentionally not set since it isn't considered the concern of `gimme` :smile_cat:
