### ISSUE TITLE
/usr/local/bin/gimme: line 240: /home/travis/.gimme/versions/go1.5.darwin.amd64/bin/go: cannot execute binary file

### ISSUE THREAD

**Issue by petemoore** [travis-ci/gimme#25]
See e.g. https://travis-ci.org/taskcluster/livelog/jobs/93377580#L97

For some reason, the version of gimme has regressed on travis to v0.2.2. Previous runs had v0.2.3. Maybe this is the cause?

**Comment by petemoore** [comment]
I have a workaround in place for now, which others can also use if they hit this.

**Obviously replace the `1.5` reference below with the version of go you need!**

```
# workaround for travis-ci/gimme#25 to pick up latest version of gimme and run again
before_install:
  - curl -o gimme -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod u+x gimme
  - unset GOROOT GOTOOLDIR
  - eval "$(./gimme 1.5)"
  - go version
  - go env
```

This workaround downloads the latest version of gimme which seems to have resolved the problem (I believe gimme v0.2.2 is currently included in the travis worker image which contains this bug) and then runs gimme again. Note, it can take a short while to download and install go, seemingly longer than before (suspect no cache is available).

**Comment by petemoore** [comment]
This problem seems to still be occurring as I still need the workaround for correct behavior. Is anybody else experiencing this too?

**Comment by jrperritt** [comment]
Yes, we're seeing this too. Thanks for the work-around @petemoore :smile:

**Comment by ellotheth** [comment]
I stumbled over a minor improvement to the Travis-CI workaround: If you're building against multiple Go versions, you can use [`$TRAVIS_GO_VERSION`](https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables) in the `gimme` eval.

``` .yaml
before_install:
  - curl -o gimme -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod u+x gimme
  - unset GOROOT GOTOOLDIR
  - eval "$(./gimme $TRAVIS_GO_VERSION)"
  - go version
  - go env
```

**Comment by philpennock** [comment]
I'm closing this because it was about an issue already fixed in the `gimme` code-base, where the travis-ci system apparently wasn't reliably using a current gimme if the instance had an older one installed?  Nothing for `gimme` to do about that.  There have been no new reports for a year and a half, so the particular instantiation of the underlying issue has gone.

I *strongly encourage* people using `gimme` in CI tests to invoke `gimme version`, not just `go version`, so that you can see what version of `gimme` was used.  The same goes for any tools used in CI building -- you have a log of output, put useful things in it!  Eg, I have a `show-versions` Make target available for use in some of my stuff, just to handle this.  Make it a dependency of the target used for building.
