### ISSUE TITLE
Treat omission of patch version as latest patch in given minor release

### ISSUE THREAD

**Issue by zombiezen** [travis-ci/gimme#69]
(Please dedupe if this is already known, but I haven't found an issue for this yet.)

AFAICT, if you specify `gimme 1.6`, Go 1.6.0 will be downloaded.  Most people I talk to are not aware of this behavior, and would expect Go 1.6.X to be downloaded, where X is the largest number that exists (3 at time of writing).  This is also an ongoing maintenance burden for many projects that I own, where every time there is a Go patch, I must update my repos' Travis configs to use the latest patch of Go.

I propose that you should need to specify `gimme 1.6.0` in order to download `https://storage.googleapis.com/golang/go1.6.src.tar.gz` or similar.

**Comment by meatballhat** [comment]
@zombiezen Sorry for the delay.  This is something we addressed [at a different level specifically for use at Travis CI, by aliasing versions accordingly](https://github.com/travis-ci/travis-build/blob/524f3d812400cbe3aad2a6f332fe748c41bcce65/lib/travis/build/script/go.rb#L18-L33) such that `1.6.x` gets the latest `1.6.x`, whereas `1.6` means `1.6`, since `1.6` is a valid golang release number.  I realize this is somewhat confusing if one expects the version number to always be in the form `\d+\.\d+\.\d+`.  The reasons for why we went with the solution that's in place include a desire to keep `gimme` as naïve as possible, and not wanting to mask, predict, or otherwise interpret the intentions of the Golang team wrt version numbers.

I'm realizing while writing this that the support for, e.g. `1.6.x` in one's `.travis.yml` is not currently document behavior, which I'll go and fix now :+1:.
