### ISSUE TITLE
Does not seem to set Go version

### ISSUE THREAD

**Issue by georgeu2000** [travis-ci/gimme#73]
```
$ gimme 1.7.3
unset GOOS
unset GOARCH
export GOROOT="/home/travis/.gimme/versions/go1.7.3.linux.amd64"
export PATH="/home/travis/.gimme/versions/go1.7.3.linux.amd64/bin:${PATH}"
go version >&2
export GIMME_ENV="/home/travis/.gimme/envs/go1.7.3.env"
$ go version
go version go1.4.1 linux/amd64
```

Installed 1.7.3 but when I use go I get version 1.4.1. PATH appears to be set.

Working on Travis CI.

**Comment by philpennock** [comment]
You've missed the need to `eval` the output of the command.

In Unix systems, processes form a hierarchy and the environment is not shared between all processes but instead can be set by a process upon itself and inherited by new children spawned thereafter (simplifying a little).

You need: `eval "$(gimme 1.7.3)"`

The shell will run the command, capture the stdout (but not the stderr, thus the version output being sent to stderr) and then evaluate it as shell commands.

Also: if you update gimme to a newer version, then the output would have semi-colons at the end of each command.  Because you're on an old version, you *must* include the double-quotes around the command substitution, to preserve newlines.  Be careful to copy/paste exactly.

I'm going to close this ticket but if the problem persists and what I've said doesn't help, please do re-open.

**Comment by georgeu2000** [comment]
Thanks for the explanation.
