### ISSUE TITLE
go: "1.8.x" don't work for last released Go version

### ISSUE THREAD

**Issue by msoap** [travis-ci/gimme#85]
`go: "1.8.x"` in `.tarvis.ci` takes go1.8rc1 Go version instead of 1.8
but `go: "1.8"` - works properly

.travis.yml - https://github.com/msoap/yandex-weather-cli/blob/master/.travis.yml#L11
logs: https://travis-ci.org/msoap/yandex-weather-cli/jobs/202555565#L153

also `go: "1.7.x"` takes 1.7.4 instead of 1.7.5: [logs](https://travis-ci.org/msoap/yandex-weather-cli/jobs/202555564#L142)

**Comment by sagikazarmark** [comment]
One would assume Travis follows language changes faster.

**Comment by dmitshur** [comment]
Also, `1.x` gives me 1.7.4 instead of 1.8. /cc @meatballhat

`.travis.yml` with Go `1.x`: https://github.com/shurcooL/trayhost/blob/333e9dcae10/.travis.yml#L5.
Failed build with Go `1.x`: https://travis-ci.org/shurcooL/trayhost/builds/202835104.
Its log says `go version go1.7.4 darwin/amd64`.

Note that this particular `.travis.yml` sets `os: osx`.

Is there an ETA on fixing this? I expect `1.x` to fetch 1.8 since that's the latest stable release (source: https://groups.google.com/forum/#!topic/golang-announce/7q2AdUHAuuI), and my tests depend on 1.8+ APIs to pass. I need to know if I should wait, or start to revert my Go 1.8-only changes.

Thank you!

**Comment by tianon** [comment]
This is actually a feature of Travis, not of `gimme`; I've filed https://github.com/travis-ci/travis-build/pull/961 over there to update their alias references. :+1:

**Comment by msoap** [comment]
Thanks!
