### ISSUE TITLE
GOROOT suppressed, should be overridden

### ISSUE THREAD

**Issue by philpennock** [travis-ci/gimme#87]
The gimme tooling explicitly unsets `GOROOT` in environ.  If `/usr/local/go` exists, then `GOROOT` points there, so even if you choose a different Go version with `gimme`, the `GOTOOLDIR` commands (`cgo`, `pprof` etc) will be the system variants, not this Go's variants.

Is there a reason that we're not setting `GOROOT` to be the `existing_ver`/`src_dir` directory?  I know that `GOROOT` doesn't _normally_ need to be set in environ, but I think that gimme is the corner-case where it should be.

I'm wondering if this is also the proximate cause of the #14 issues.

**Comment by mvdan** [comment]
@philpennock I experienced the same issue. In my case, Go 1.8 was installed in `/usr/local/go` and I was trying to `gimme 1.7.5`.

The workaround, for now, was to `sudo rm -rf /usr/local/go`. I know it's ugly, but it does the job just fine for our CI since we don't care about the final state of the VM.

> Is there a reason that we're not setting GOROOT to be the existing_ver/src_dir directory? I know that GOROOT doesn't normally need to be set in environ, but I think that gimme is the corner-case where it should be.

I agree. The issue is not so much that `GOROOT` isn't being pointed at the right dir, it's that it's being kept pointing at the wrong (old) one.
